# Generated by Django 3.0.7 on 2020-08-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='In',
            new_name='Info',
        ),
    ]
